--- 
user: winstijn
group: www-data
environment: production
timeout: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []

wait: 30
servers: 1
socket: /tmp/thin.AKRoosterTV_api.production.socket
daemonize: true
tag:	thin_AKRoosterTV_api
