version: '3'
services:
  app:
    container_name: "scheikunde_po"
    build:
      context: ..
      dockerfile: .deployment/Dockerfile
    # Exposes port 3000.

networks:
  default:
    external: true
    name: proxy

